triggers:
- envs: []
  last_enabled_at: null
  name: run_at_5am
  pipeline_uuid: green_taxi_etl
  schedule_interval: '@daily'
  schedule_type: time
  settings:
    timeout: '100'
  sla: null
  start_time: 2024-02-06 05:00:00
  status: inactive
  variables: {}
